### ISSUE TITLE
Wrong results from solve()-method

### ISSUE THREAD

**Issue by patriciastar** [saebyn/munkres-cpp#21]
Hi,
at first, thanks for your work. I'm trying to track two objects through a sequence of frames. I create the matrix using he distances from the object-middle-points from frame t and t+1 (so it is a 2x2 matrix). In the first few frames everything works fine, but suddenly (I debugged it) the solve-method outputs wrong results.
In the following example you can see the matrix I build and the result I get from the solve()-method:
Processing image: ...00080.jpg
11 463.289 
452.345  0 

 0 -1 
-1  0 

Processing image: ...00081.jpg
12 452.345 
440.409  0 

 0 -1 
-1  0 

Processing image: ...00082.jpg
428.476 11 
12 441.693 

 0  0 
-1  0 

When I debug in the last case (image 00082.jpg) the algorithm executes step1() correctly for the first row (STAR is set at matrix(0,1)) in the second row the algorithm comes to the for-loop and in the if-statement it outputs true for STAR == mask_matrix(0,0) -> which is not correct. 
for ( size_t nrow = 0 ; nrow < row ; nrow++ ) 
            if ( STAR == mask_matrix(nrow,col) )
That is how the above shown matrix is formed.

It would be super great if you could help me on this, because I can not work correctly with the provided results from the solve()-method.

Thanks in advance.
Best regards
Patricia

**Comment by Gluttton** [comment]
Hi!

Before I try to answer, I'd like to notice very important thing. If we want solve the problem we need to be specific and precise. It means that if we talk about some result we need show piece of code which reproduce the result!

For me the most preferable way is creation of test.
For instance: you can create one more test in the `tests/munkrestest.cpp`.
```c++
TEST_F (MunkresTest, solve_2x2_ObviousSolution_Problem1)
{
  // Arrange.
  Matrix<double> etalon_matrix{
    {-1.0,  0.0},
    { 0.0, -1.0}
  };
  Matrix<double> test_matrix{
    {428.476, 11.0},
    {12.0, 441.693}
  };

  Munkres<double> munkres;

  // Act.
  munkres.solve(test_matrix);

  // Assert.
  EXPECT_EQ (etalon_matrix, test_matrix);
}
```
Build it: `cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON .. && make tests`.
And lunch: `./tests/munkrestest --gtest_filter=*Problem*`.
```
Running main() from gtest_main.cc
Note: Google Test filter = *Problem*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MunkresTest
[ RUN      ] MunkresTest.solve_2x2_ObviousSolution_Problem1
Munkres input: Matrix:
      11, 463.289,
 452.345,       0,

Final cover count: 2
Munkres output: Matrix:
       0,      -1,
      -1,       0,

[       OK ] MunkresTest.solve_2x2_ObviousSolution_Problem1 (0 ms)
[----------] 1 test from MunkresTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

If you not familiar with tests in general or with The Google testing framework you may be prefer a small programs.
For instance create some file: `main_debug.cpp`.
```
#include "munkres.h"
#include <iostream>

int main (int /*argc*/, char ** /*argv*/)
{
    Matrix <double> matrix {
        { 11.0, 463.289}
      , {452.345, 0.0}
    };
    Munkres <double> munkres;
    std::cout << matrix << std::endl;

    munkres.solve (matrix);
    std::cout << matrix << std::endl;

    return EXIT_SUCCESS;
}
```
Build it: `g++ -std=c++11 main_debug.cpp -o main_debug -I src`.
And lunch it: `./main_debug`.
```
Matrix:
      11, 463.289,
 452.345,       0,

Matrix:
       0,      -1,
      -1,       0,
```

Both ways are acceptable.

====
So now I start to answer.

If I create tests with your input data it will pass.

```c++
TEST_F (MunkresTest, solve_2x2_ObviousSolution_Problem1)
{
  // Arrange.
  Matrix<double> etalon_matrix{
    {-1.0,  0.0},
    { 0.0, -1.0}
  };
  Matrix<double> test_matrix{
    {428.476, 11.0},
    { 12.0,  441.693}
  };

  Munkres<double> munkres;

  // Act.
  munkres.solve(test_matrix);

  // Assert.
  EXPECT_EQ (etalon_matrix, test_matrix);
}
```

```
Running main() from gtest_main.cc
Note: Google Test filter = *Problem*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MunkresTest
[ RUN      ] MunkresTest.solve_2x2_ObviousSolution_Problem1
Munkres input: Matrix:
 428.476,      11,
      12, 441.693,

Final cover count: 2
Munkres output: Matrix:
      -1,       0,
       0,      -1,

[       OK ] MunkresTest.solve_2x2_ObviousSolution_Problem1 (0 ms)
[----------] 1 test from MunkresTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```

I don't pay attention to your debug notices at this time, because I can't reproduce the result!

> It would be super great if you could help me on this

You need show your complete code snippet which reproduce the problem!


> Best regards

Good luck!

**Comment by patriciastar** [comment]
Hi,
thanks a lot for your answer. I found out, that I have to set the values of the mask_matrix to zero (or another default value) before using it the next time. Otherwise some results where kept in the matrix which let to the wrong results.

**Comment by Gluttton** [comment]
> thanks a lot for your answer.

You are welcome!

> I have to set the values of the mask_matrix to zero (or another default value) before using it the next time. 

If performance isn't crucial for your I'd like to suggest you recreate the solver each time.

Instead:
```c++
Munkres <double> solver;
std::vector <Matrix <double> > problems;
for (auto & problem : problems) {
    solver.solve (problem);
}
```
I suggest use:
```c++
std::vector <Matrix <double> > problems;
for (auto & problem : problems) {
    Munkres <double> solver;
    solver.solve (problem);
}
```
In this case the correct result is guaranteed by existed tests.
